export const SELECT_CATEGORY = 'SELECT_CATEGORY';

export const SELECT_PLACE = 'SELECT_PLACE';
export const GET_PLACE_SUCCESS = 'GET_PLACE_SUCCESS';

export const GET_CONTENT_SUCCESS = 'GET_CONTENT_SUCCESS';
export const SELECT_CONTENT = 'SELECT_CONTENT';

export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';

export const GET_TOPS_SUCCESS = 'GET_TOPS_SUCCESS';
